# Generated by Django 3.2.25 on 2025-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='information',
            field=models.CharField(max_length=1000),
        ),
    ]
