# Generated by Django 3.2.25 on 2025-11-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('village_image', models.ImageField(upload_to='village_images/')),
                ('current_village_image', models.ImageField(upload_to='current_village_images/')),
                ('my_image1', models.ImageField(upload_to='my_images/')),
                ('my_image2', models.ImageField(upload_to='my_images/')),
                ('my_image3', models.ImageField(upload_to='my_images/')),
            ],
        ),
    ]
